source 'http://rubygems.org'

gem 'sinatra', '~> 2.0.2'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'rack-flash3'
gem 'bcrypt'
